Kurdish translation
ReCoded-Org/capstone-iraq-rct-paw-five pull request #66
Opened 2021-04-03 16:12 UTC by Ali-mustafa8

2021-04-03 16:24 UTC, MuhannedNoman commented
Hey @Faeza97 , please take a look.

2021-04-04 05:56 UTC, Faeza97 requested changes
@Ali-mustafa8  please check my review.
thanks

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
>      "home": "سەرەکی",
لاپەڕەی سەرەکی یان ماڵەوە

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "required": "پڕکردنەوەی ئەو خانەیە داواکراوە",
ئەم 
لە جێگای ئەو

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "example-number": " 07700000000 ژمارەی تەلەفۆنەکەت پێویستە بەو شێوەیە بێت",
مۆبایل لە جێگای تەلەفۆن

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "phone-validation": "ژمارەی مۆبالیکەت پێویستە لە ١١ خانە پێکهاتبێت",
مۆبایلەکەت

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "age-validation": "تەمەنی ئاژەڵەکە پێویستە لە دوو ژمارە کەمتر نەبێت",
گیانەوەرە ماڵیەکە

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "addapet": "زیادکردنی ئاژەڵ",
Pet -> گیانەوەری ماڵی

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "add for adoption": "زیادکردنی ئاژەڵ بۆ هەڵگرتنەوە",
گیانەوەری ماڵی یان ئاژەڵی ماڵی

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "make-pets-happy": " لێرە دەتوانی ئاژەڵیك دابنێی بۆ هەڵگرتنەوە بۆ ئەوەی دڵخۆش و پارێزراو بێت",
هەموو ئاژەڵەکان بگۆڕە بۆ 
ئاژەڵی ماڵی یان گیانەوەری ماڵی یان گیانداری ماڵی

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "gender": "رەگەزی ئاژەڵەکە (ئارەزوومەندنە)",
ئارەزوومەندانە

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "upload-photo": "وێنەیەک بێنە",
وێنەیەک هەڵبژێرە

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "contact-info": "Contact Info",
زانیاری پەیوەندیکردن

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "aboutOwner": "دەربارەی خاوەنەکی",
خاوەنەکەی

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "email":"هەژماری ئەلکترۆنی",
ئەلیکترۆنی

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "required":"پڕکردنەوەی ئەو خانەیە داواکراوە",
ئەم

2021-04-04 05:56 UTC, Faeza97 commented on src/translations/krd/translation.json
> +    "h6text":"customers served"
خزمەتکراون

2021-04-05 16:04 UTC, MuhannedNoman commented
Solved in #70

2021-04-05 16:04 UTC, closed without merging